name: Daily Leave Report Upload to Google Sheet

on:
  schedule:
    - cron: "0 23 * * *"  # 7 AM Malaysia
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas xlrd openpyxl google-auth google-auth-httplib2 google-api-python-client

      - name: Install Playwright browser
        run: playwright install chromium

      - name: Run automation script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python main.py
