name: Daily Leave Report to Google Drive

on:
  schedule:
    - cron: "0 23 * * *"  # Runs daily at 7 AM Malaysia (GMT+8 = 23:00 UTC)
  workflow_dispatch:      # Allow manual run

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          playwright install chromium

      - name: Run Playwright script (download Excel)
        run: python main.py

      - name: Upload to Google Drive
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: python upload_to_drive.py
