name: Web Automation Bot

on:
  schedule:
    - cron: "0 1 * * *"  # Runs daily at 1 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Run automation
        run: python main.py
